marks1=int(input("Enter marks 1:"))
marks2=int(input("Enter marks 2:"))
marks3=int(input("Enter marks 3:"))
marks4=int(input("Enter marks 4:"))
marks5=int(input("Enter marks 5:"))
marks6=int(input("Enter marks 6:"))
marksList=[marks1,marks2, marks3,marks4,marks5,marks6]
marksList.sort()
print(marksList)
marksList.reverse()
print(marksList)
